// Generated by https://quicktype.io
export type BlockType = 
    | 'paragraph' | 'heading_1' | 'heading_2' | 'heading_3' 
    | 'bulleted_list_item' |'numbered_list_item' |'toggle'
    | 'divider' | 'video' | 'image' | 'table' | 'table_row'

export interface INotionPage {
    meta:   Meta;
    blocks: Block[];
}

export type Block = {
    [key in BlockType]: BlockContent;
} & {
    object: string;
    id: string;
    parent: BlockParent;
    created_time: string;
    last_edited_time: string;
    created_by: TedBy;
    last_edited_by: TedBy;
    has_children: boolean;
    archived: boolean;
    type: BlockType;
};

export interface TedBy {
    object: string;
    id:     string;
}

export interface BlockContent {
    rich_text: RichText[];
    color:     string;
    caption:   []
    type:      'external'
    external:  {
        url:    string
    }
    has_column_header?: boolean
    has_row_header?:    boolean
    cells?:   RichText[][]
    results?: Block[]
}

export interface RichText {
    type:        string;
    text:        Text;
    annotations: Annotations;
    plain_text:  string;
    href:        null;
}

export interface Annotations {
    bold:          boolean;
    italic:        boolean;
    strikethrough: boolean;
    underline:     boolean;
    code:          boolean;
    color:         string;
}

export interface Text {
    content: string;
    link:    null | { url: string };
}

export interface BlockParent {
    type:    string;
    page_id: string;
}

export interface Meta {
    object:           string;
    id:               string;
    created_time:     string;
    last_edited_time: string;
    created_by:       TedBy;
    last_edited_by:   TedBy;
    cover:            null;
    icon:             null;
    parent:           MetaParent;
    archived:         boolean;
    properties:       Properties;
    url:              string;
}

export interface MetaParent {
    type:        string;
    database_id: string;
}

export interface Properties {
    Date: DateClass;
    Tags: Tags;
    Name: Name;
}

export interface DateClass {
    id:   string;
    type: string;
    date: null;
}

export interface Name {
    id:    string;
    type:  string;
    title: RichText[];
}

export interface Tags {
    id:           string;
    type:         string;
    multi_select: any[];
}